[package]
name = "throttle-cpu-temp"
version = "0.1.1"
authors = ["Antonio Zanardo <zanardo@gmail.com>"]

[dependencies]
num_cpus = "1.0"
simplelog = "^0.4.2"
log = "0.3"
timer = "0.2.0"
chrono = "0.4.1"
chan = "^0.1.21"
